#Scenario 1
URLValidation= simple-form-demo
message= Welcome to LambdaTest

#Scenario 2
output= 95
outputMessage= Slider value should be 95

#Scenario 3
userName= Mathew
password= Mathew@1997
companyName= Elfonze
website= elfonze.com
country= United States
city= Bangalore
address1= 40/1A, Lavelle Road, Bengaluru, Karnataka
address2= 6th Floor, STPI ELITE Tower, Bhubaneswar
state= Karnataka
pinCode= 560001