url=https://www.lambdatest.com/selenium-playground
browserName=chrome
userName=Mathew
validUserName=mathewyabes@gmail.com
validPassword=Mathew@1997
homePageURL=https://tutorialsninja.com/demo/index.php?route=common/home